Update functions to support recording
twilio/twilio-live-interactive-video pull request #111
Opened 2022-04-13 06:38 UTC by timmydoza

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [VIDEO-0000](https://issues.corp.twilio.com/browse/VIDEO-0000)

### Description

A description of what this PR does.

## Burndown

### Before review
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with all effected platforms
* [ ] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

2022-04-20 17:46 UTC, timrozum approved these changes
Looks like the new error handling will make the code a lot easier to follow!

2022-04-25 19:29 UTC, olipyskoty requested changes
Looks good, and a lot more readable! Found a couple of typos, otherwise looks great.

2022-04-25 19:29 UTC, olipyskoty commented on serverless/functions/media-processor-webhook.js
> +  const { axiosClient, response, getStreamMapItem, createErrorHandler } = common(context, event, callback);
are `axiosClient` and `response` being used?

2022-04-25 19:29 UTC, olipyskoty commented on serverless/functions/media-processor-webhook.js
> +      .update({ data: { ...doc.data, recording: { is_recording: false, error: 'A recording error has occured' } } })
should be `occurred`🙂

2022-04-25 19:29 UTC, olipyskoty commented on serverless/functions/join-stream-as-speaker.js
> +        createErrorHandler('error adding read access to user document')(error);
Should this error message explain that there was an error adding the participant to the conversation?  i.e. `'error creating conversation participant'`

2022-05-03 21:02 UTC, timmydoza commented
Good eye @olipyskoty! I fixed those issues. 

@timrozum - I also went ahead and removed the `sync_object_names` from the responses as we discussed.

2022-05-03 22:10 UTC, olipyskoty approved these changes
🎉

2022-06-09 21:04 UTC, merged