Video 9638 web implement chat
twilio/twilio-live-interactive-video pull request #120
Opened 2022-05-10 20:40 UTC by olipyskoty

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [VIDEO-9638](https://issues.corp.twilio.com/browse/VIDEO-9638)

### Description

This PR adds the audience chat to the web livestreaming app. Viewers can now view the chat and send messages.

## Burndown

### Before review
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with all effected platforms
* [x] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [x] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

2022-05-11 21:33 UTC, timrozum approved these changes
Room SID stuff looks good.

2022-06-21 04:13 UTC, timmydoza requested changes
I think this looks good, but some merge conflicts have appeared. @olipyskoty would you mind taking a look at these conflicts and then I'll take another look.

2022-06-22 15:43 UTC, timmydoza commented on apps/web/src/components/Player/PlayerMenuBar/PlayerMenuBar.tsx
> +
This is kinda funny - just that these two pieces of state that control two sidebars live in two different places. Not sure it's worth fixing now though.

2022-06-22 15:43 UTC, timmydoza commented on apps/web/src/components/PreJoinScreens/PreJoinScreens.tsx
> +          chatConnect(data.token, data.room_sid);
Should this one be behind `if (data.chat_enabled) {` too?

2022-06-22 16:58 UTC, timmydoza approved these changes

2022-06-22 16:59 UTC, merged